package ihommani;

import org.assertj.core.api.AbstractAssert;
// Assertions is needed if an assertion for Iterable is generated
import org.assertj.core.api.Assertions;


/**
 * {@link RelationType} specific assertions - Generated by CustomAssertionGenerator.
 */
public class RelationTypeAssert extends AbstractAssert<RelationTypeAssert, RelationType> {

  /**
   * Creates a new </code>{@link RelationTypeAssert}</code> to make assertions on actual RelationType.
   * @param actual the RelationType we want to make assertions on.
   */
  public RelationTypeAssert(RelationType actual) {
    super(actual, RelationTypeAssert.class);
  }

  /**
   * An entry point for RelationTypeAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one's can write directly : <code>assertThat(myRelationType)</code> and get specific assertion with code completion.
   * @param actual the RelationType we want to make assertions on.
   * @return a new </code>{@link RelationTypeAssert}</code>
   */
  public static RelationTypeAssert assertThat(RelationType actual) {
    return new RelationTypeAssert(actual);
  }

  /**
   * Verifies that the actual RelationType's declaringClass is equal to the given one.
   * @param declaringClass the given declaringClass to compare the actual RelationType's declaringClass to.
   * @return this assertion object.
   * @throws AssertionError - if the actual RelationType's declaringClass is not equal to the given one.
   */
  public RelationTypeAssert hasDeclaringClass(Class declaringClass) {
    // check that actual RelationType we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String errorMessage = "\nExpected declaringClass of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    Class actualDeclaringClass = actual.getDeclaringClass();
    if (!org.assertj.core.util.Objects.areEqual(actualDeclaringClass, declaringClass)) {
      failWithMessage(errorMessage, actual, declaringClass, actualDeclaringClass);
    }

    // return the current assertion for method chaining
    return this;
  }

}
